

name: New bulletin
on:
  schedule:
    - cron:  '*/10 7-17 * * 1-6'

  workflow_dispatch:
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.outputs.date }}
      branch: ${{ steps.branch.outputs.branch }}

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Define branch name
        id: branch
        run: echo "::set-output name=branch::bocm/${{ steps.date.outputs.date }}"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Switch to ${{ steps.branch.outputs.branch }}
        run: (git show-branch ${{ steps.branch.outputs.branch }} &>/dev/null) && (git checkout ${{ steps.branch.outputs.branch }}) || (git checkout -b ${{ steps.branch.outputs.branch }})

      - name: Pull brach ${{ steps.branch.outputs.branch }}
        run: git pull origin ${{ steps.branch.outputs.branch }}
        continue-on-error: true

      - name: Push branch ${{ steps.branch.outputs.branch }}
        run: git push origin ${{ steps.branch.outputs.branch }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout ${{ needs.setup.outputs.branch }}
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.setup.outputs.branch }}
          persist-credentials: true
          fetch-depth: 0

      - name: Install Dependencies
        run: npm ci

      - name: Setup notifications
        run: npm run start

      - name: Commit & Push data and notifications
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Notifications generated for ${{ needs.setup.outputs.date }}
          branch: ${{ needs.setup.outputs.branch }}

  send:
    name: Send next notification
    runs-on: ubuntu-latest
    env:
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY}}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    needs:
      - setup
      - build
    steps:
      - name: Checkout ${{ needs.setup.outputs.branch }}
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.setup.outputs.branch }}
          persist-credentials: true
          fetch-depth: 0

      - name: Install Dependencies
        run: npm ci

      - name: Send next notifications
        run: npm run send-next

      - name: Commit & Push notifications data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Remove sent notification
          branch: ${{ needs.setup.outputs.branch }}
